apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-k8s
  template:
    metadata:
      labels:
        app: spring-k8s
    spec:
      containers:
      - name: spring-k8s
        image: spring-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
